version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.0
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Setup Dependencies
          command: yarn install
  notify_job_status:
    description: Send webhook to Telegram BOT about job statuss
    docker:
      - image: circleci/node:11.0
    steps:
      - run:
          name: On success
          when: on_success
          command: |
            curl https://stark-badlands-85096.herokuapp.com/notification -d '{"payload":{"reponame":"'"$CIRCLE_PROJECT_REPONAME"'", "repourl":"'"$CIRCLE_REPOSITORY_URL"'", "username":"'"$CIRCLE_PR_USERNAME"'", "branch":"'"$CIRCLE_BRANCH"'", "build_url":"'"$CIRCLE_BUILD_URL"'", "status":"succeed"}}' -H "Content-Type: application/json" -X POST --fail
      - run:
          name: On fail
          when: on_fail
          command: |
            curl https://stark-badlands-85096.herokuapp.com/notification -d '{"payload":{"reponame":"'"$CIRCLE_PROJECT_REPONAME"'", "repourl":"'"$CIRCLE_REPOSITORY_URL"'", "username":"'"$CIRCLE_PR_USERNAME"'", "branch":"'"$CIRCLE_BRANCH"'", "build_url":"'"$CIRCLE_BUILD_URL"'", "status":"failed"}}' -H "Content-Type: application/json" -X POST --fail

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - notify_job_status:
          requires:
            - build
